### ISSUE TITLE
A macro that  concatenates multiline strings

### ISSUE THREAD

**Issue by mslinn** [davegurnell/unindent#1]
A macro that  concatenates multiline strings into one line would be helpful. Two successive newlines would produce a newline.

**Comment by davegurnell** [comment]
Thanks @mslinn. Sorry it's taken me so long to get to this. You've got a good suggestion there and it'd be super easy to code.

**Comment by davegurnell** [comment]
Unindent v1.7 contains a new `i1"..."` interpolator that folds line endings similarly to folded strings in YAML.  🎉 

More details in the README. Thanks to @DroneEnthusiast for the contribution!
